export const landingCopy = {
  th: {
    nav: {
      home: 'หน้าแรก',
      products: 'สินค้า',
      benefits: 'ประโยชน์',
      testimonials: 'รีวิว',
      blog: 'บทความ',
      videos: 'วิดีโอ',
      admin: 'แอดมิน',
      contact: 'ติดต่อ',
      login: 'เข้าสู่ระบบ',
      buyNow: 'สั่งซื้อเลย',
    },
    hero: {
      badge: 'ลดพิเศษ! ปกติ 850.- เหลือ 790.-',
      title: 'วิธีที่ Nano Zinco ช่วยทุกเรื่องของคุณ',
      subtitle: 'เสริมภูมิคุ้มกัน บำรุงผิวและสายตา ลดความอ่อนล้า พร้อมดูแลร่างกายให้สดชื่นตลอดวัน',
      ctaPrimary: 'สั่งซื้อเลย',
      ctaSecondary: 'เก็บเงินปลายทางได้',
      tag: 'ขายดีอันดับ 1',
      promo: 'ลดทันที 60.-',
    },
    product: {
      title: 'สินค้าเด่น พร้อมโปรโมชัน',
      description: 'Nano Zinco สูตรเข้มข้น ดูดซึมง่าย เหมาะสำหรับทุกวัย',
      saleLabel: 'Sale + Promotion',
    },
    benefits: {
      title: 'Nano Zinco ช่วยให้ร่างกายดีขึ้นอย่างไร',
      items: [
        'เสริมภูมิคุ้มกัน ให้ร่างกายแข็งแรง',
        'ช่วยบำรุงผิวพรรณ ลดสิวและความมัน',
        'ฟื้นฟูพลังงาน ลดความอ่อนล้า',
        'ดูแลสายตาและระบบเผาผลาญ',
      ],
    },
    showcase: {
      title: 'ผลลัพธ์ที่คนเลือกซ้ำ',
      items: [
        { title: 'ตื่นเช้าสดชื่น', description: 'พลังงานเต็มวัน ทำงานได้นานขึ้น' },
        { title: 'ผิวดูสุขภาพดี', description: 'ลดสิว ผิวกระจ่างใสขึ้น' },
        { title: 'ภูมิคุ้มกันดีขึ้น', description: 'ไม่ค่อยป่วยง่ายเหมือนเดิม' },
      ],
    },
    testimonials: {
      title: 'เสียงจากผู้ใช้จริง',
      items: [
        { name: 'คุณแอน', text: 'รู้สึกสดชื่นขึ้น ตื่นมาพร้อมพลังทุกวัน' },
        { name: 'คุณบีม', text: 'ผิวดีขึ้นอย่างเห็นได้ชัด แถมไม่อ่อนเพลีย' },
        { name: 'คุณกอล์ฟ', text: 'ช่วยเสริมภูมิ ทำงานหนักก็ยังไหว' },
      ],
    },
    buyNow: {
      title: 'สั่งซื้อได้ทันที',
      description: 'ชำระผ่านโอนธนาคาร หรือเก็บเงินปลายทางได้',
      bank: 'โอนธนาคาร',
      cod: 'เก็บเงินปลายทาง',
    },
    coupon: {
      title: 'คูปองส่วนลดพิเศษ',
      description: 'รับส่วนลดเพิ่มเมื่อสั่งซื้อผ่าน Zinco APP',
      code: 'ZINCOAPP10',
      note: 'ส่วนลดพิเศษเฉพาะในแอป',
    },
    app: {
      title: 'ดาวน์โหลดแอป Zinco',
      description: 'รับโปรโมชั่นและติดตามสุขภาพครบวงจร',
      badge: 'รับส่วนลดทันที',
    },
    blog: {
      title: 'บทความล่าสุด',
      subtitle: 'เคล็ดลับสุขภาพและสาระดีๆ',
      cta: 'อ่านบทความทั้งหมด',
    },
    videos: {
      title: 'วิดีโอจากเรา',
      subtitle: 'คลังวิดีโอ Nano Zinco',
      cta: 'ดูวิดีโอทั้งหมด',
    },
    contact: {
      title: 'ติดต่อเรา',
      call: 'โทร',
      facebook: 'Facebook',
      line: 'Line',
      tiktok: 'TikTok',
    },
    admin: {
      title: 'ส่วนแอดมิน',
      description: 'ดูออเดอร์และยอดสั่งซื้อล่าสุด',
    },
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      benefits: 'Benefits',
      testimonials: 'Reviews',
      blog: 'Blog',
      videos: 'Videos',
      admin: 'Admin',
      contact: 'Contact',
      login: 'Login',
      buyNow: 'Buy Now',
    },
    hero: {
      badge: 'Special Deal! From 850 to 790',
      title: 'How Nano Zinco helps you feel better',
      subtitle: 'Boost immunity, support skin and vision, and reduce fatigue for daily energy.',
      ctaPrimary: 'Buy Now',
      ctaSecondary: 'Cash on Delivery',
      tag: '#1 Best Seller',
      promo: 'Instant 60 off',
    },
    product: {
      title: 'Featured Product + Promotion',
      description: 'High-absorption zinc formula for everyday wellness.',
      saleLabel: 'Sale + Promotion',
    },
    benefits: {
      title: 'How Nano Zinco improves your body',
      items: [
        'Stronger immunity and resilience',
        'Supports clearer skin and balance',
        'Restores energy and reduces fatigue',
        'Supports vision and metabolism',
      ],
    },
    showcase: {
      title: 'Results people love',
      items: [
        { title: 'Wake up refreshed', description: 'More energy for a full day' },
        { title: 'Healthier skin', description: 'Less breakouts and better tone' },
        { title: 'Better immunity', description: 'Fewer colds and stronger body' },
      ],
    },
    testimonials: {
      title: 'Real testimonials',
      items: [
        { name: 'Ann', text: 'I feel more refreshed and energized every day.' },
        { name: 'Beam', text: 'My skin looks better and I feel less tired.' },
        { name: 'Golf', text: 'Great for immunity even during busy weeks.' },
      ],
    },
    buyNow: {
      title: 'Buy instantly',
      description: 'Pay by bank transfer or cash on delivery.',
      bank: 'Bank Transfer',
      cod: 'Cash on Delivery',
    },
    coupon: {
      title: 'Extra discount coupon',
      description: 'Get more discount when ordering through Zinco APP',
      code: 'ZINCOAPP10',
      note: 'App-only special discount',
    },
    app: {
      title: 'Download the Zinco app',
      description: 'Promotions, health tracking, and more',
      badge: 'Instant discount',
    },
    blog: {
      title: 'Latest posts',
      subtitle: 'Health tips and insights',
      cta: 'Read all posts',
    },
    videos: {
      title: 'Our videos',
      subtitle: 'Nano Zinco video library',
      cta: 'Watch all videos',
    },
    contact: {
      title: 'Contact',
      call: 'Call',
      facebook: 'Facebook',
      line: 'Line',
      tiktok: 'TikTok',
    },
    admin: {
      title: 'Admin section',
      description: 'See orders and latest purchases',
    },
  },
  zh: {
    nav: {
      home: '首页',
      products: '产品',
      benefits: '功效',
      testimonials: '评价',
      blog: '博客',
      videos: '视频',
      admin: '管理',
      contact: '联系',
      login: '登录',
      buyNow: '立即购买',
    },
    hero: {
      badge: '特价! 原价850 现价790',
      title: 'Nano Zinco 如何让你更好',
      subtitle: '提升免疫力，支持皮肤与视力，减少疲劳，保持活力。',
      ctaPrimary: '立即购买',
      ctaSecondary: '货到付款',
      tag: '畅销第1名',
      promo: '立减60',
    },
    product: {
      title: '热销产品与优惠',
      description: '高吸收锌配方，适合每日保健。',
      saleLabel: '特价 + 优惠',
    },
    benefits: {
      title: 'Nano Zinco 如何改善身体',
      items: [
        '增强免疫力与抵抗力',
        '支持皮肤健康与平衡',
        '恢复能量，减少疲劳',
        '支持视力与代谢',
      ],
    },
    showcase: {
      title: '大家喜欢的效果',
      items: [
        { title: '早晨更清醒', description: '更有精力完成一天' },
        { title: '皮肤更健康', description: '痘痘减少，状态更好' },
        { title: '免疫更强', description: '更少感冒，身体更稳' },
      ],
    },
    testimonials: {
      title: '真实用户评价',
      items: [
        { name: 'Ann', text: '每天都更有精神，状态更好。' },
        { name: 'Beam', text: '皮肤改善明显，也不容易疲劳。' },
        { name: 'Golf', text: '忙碌的时候也能维持免疫力。' },
      ],
    },
    buyNow: {
      title: '立即购买',
      description: '支持银行转账或货到付款',
      bank: '银行转账',
      cod: '货到付款',
    },
    coupon: {
      title: '额外折扣券',
      description: '通过 Zinco APP 下单可获得更多优惠',
      code: 'ZINCOAPP10',
      note: 'App 专享折扣',
    },
    app: {
      title: '下载 Zinco 应用',
      description: '优惠、健康追踪一站式服务',
      badge: '立享优惠',
    },
    blog: {
      title: '最新文章',
      subtitle: '健康建议与资讯',
      cta: '查看全部',
    },
    videos: {
      title: '我们的视频',
      subtitle: 'Nano Zinco 视频库',
      cta: '查看全部',
    },
    contact: {
      title: '联系我们',
      call: '电话',
      facebook: 'Facebook',
      line: 'Line',
      tiktok: 'TikTok',
    },
    admin: {
      title: '管理后台',
      description: '查看订单与最新购买',
    },
  },
};
