export const checkoutCopy = {
  th: {
    title: 'ชำระเงิน',
    subtitle: 'กรอกข้อมูลจัดส่งและเลือกวิธีชำระเงิน',
    shipping: 'ข้อมูลจัดส่ง',
    name: 'ชื่อ-นามสกุล',
    phone: 'เบอร์โทร',
    address: 'ที่อยู่จัดส่ง',
    payment: 'วิธีชำระเงิน',
    bank: 'โอนธนาคาร',
    cod: 'เก็บเงินปลายทาง',
    note: 'หมายเหตุ',
    placeOrder: 'ยืนยันคำสั่งซื้อ',
    summary: 'สรุปรายการ',
    total: 'ยอดรวม',
    cart: 'ตะกร้า',
    loading: 'กำลังโหลด...',
    bankHint: 'KBANK XXX-X-XXXXX-X',
    codHint: 'ชำระเงินเมื่อรับสินค้า',
    empty: 'ยังไม่มีสินค้าในตะกร้า',
    backToProducts: 'กลับไปเลือกสินค้า',
  },
  en: {
    title: 'Checkout',
    subtitle: 'Enter shipping details and choose payment method',
    shipping: 'Shipping details',
    name: 'Full name',
    phone: 'Phone',
    address: 'Shipping address',
    payment: 'Payment method',
    bank: 'Bank transfer',
    cod: 'Cash on delivery',
    note: 'Note',
    placeOrder: 'Place order',
    summary: 'Order summary',
    total: 'Total',
    cart: 'Cart',
    loading: 'Loading...',
    bankHint: 'KBANK XXX-X-XXXXX-X',
    codHint: 'Pay when receiving items',
    empty: 'Your cart is empty',
    backToProducts: 'Back to products',
  },
  zh: {
    title: '结账',
    subtitle: '填写配送信息并选择支付方式',
    shipping: '配送信息',
    name: '姓名',
    phone: '电话',
    address: '收货地址',
    payment: '支付方式',
    bank: '银行转账',
    cod: '货到付款',
    note: '备注',
    placeOrder: '提交订单',
    summary: '订单概览',
    total: '总计',
    cart: '购物车',
    loading: '加载中...',
    bankHint: 'KBANK XXX-X-XXXXX-X',
    codHint: '收货时付款',
    empty: '购物车为空',
    backToProducts: '返回产品页',
  },
};

export const adminCopy = {
  th: {
    title: 'แอดมินแดชบอร์ด',
    subtitle: 'ตรวจสอบคำสั่งซื้อและยอดล่าสุด',
    latestOrders: 'คำสั่งซื้อล่าสุด',
    latestPurchase: 'ยอดสั่งซื้อล่าสุด',
    empty: 'ยังไม่มีข้อมูลจากระบบ',
    setup: 'โปรดตั้งค่า NEXT_PUBLIC_ADMIN_API_BASE_URL',
    loading: 'กำลังโหลด...',
  },
  en: {
    title: 'Admin dashboard',
    subtitle: 'Track orders and recent purchases',
    latestOrders: 'Latest orders',
    latestPurchase: 'Latest purchase',
    empty: 'No data available',
    setup: 'Please set NEXT_PUBLIC_ADMIN_API_BASE_URL',
    loading: 'Loading...',
  },
  zh: {
    title: '管理控制台',
    subtitle: '查看订单与最新购买',
    latestOrders: '最新订单',
    latestPurchase: '最新购买',
    empty: '暂无数据',
    setup: '请设置 NEXT_PUBLIC_ADMIN_API_BASE_URL',
    loading: '加载中...',
  },
};

export const blogCopy = {
  th: {
    title: 'บทความ',
    subtitle: 'เคล็ดลับสุขภาพและสาระดีๆ',
  },
  en: {
    title: 'Blog',
    subtitle: 'Health tips and insights',
  },
  zh: {
    title: '博客',
    subtitle: '健康建议与资讯',
  },
};

export const videosCopy = {
  th: {
    title: 'วิดีโอ',
    subtitle: 'คลังวิดีโอของ Nano Zinco',
    upload: 'อัปโหลดวิดีโอ',
    uploadHint: 'เลือกไฟล์วิดีโอเพื่อดูตัวอย่าง (ยังไม่บันทึกลงระบบ)',
  },
  en: {
    title: 'Videos',
    subtitle: 'Nano Zinco video library',
    upload: 'Upload video',
    uploadHint: 'Select a video to preview (not saved to server yet)',
  },
  zh: {
    title: '视频',
    subtitle: 'Nano Zinco 视频库',
    upload: '上传视频',
    uploadHint: '选择视频预览 (暂未保存到服务器)',
  },
};
